spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://192.168.56.4:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.mppm: DEBUG

