spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mppm}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.mppm: INFO

